const WORD_LISTS = {
  tr: {
    basic: [
      "bir","iki","üç","dört","beş","altı","yedi","sekiz","dokuz","on","yüz","bin",
      "ve","bu","da","de","ki","ne","su","ev","iş","el","göz","baş","yol","gün","yıl","ay",
      "yer","zaman","adam","kadın","çocuk","anne","baba","kardeş","arkadaş","insan",
      "araba","okul","kitap","masa","sandalye","kapı","pencere","alan","ada","il",
      "büyük","küçük","hızlı","yavaş","iyi","kötü","güzel","çirkin","uzun","kısa",
      "sevmek","yemek","içmek","gitmek","gelmek","almak","vermek","görmek","bilmek",
      "düşünmek","yazmak","okumak","çalışmak","oynamak","uyumak","beklemek","söylemek",
      "tam","az","çok","hep","hiç","daha","en","son","ilk","her","bazı","artık",
      "ben","sen","o","biz","siz","onlar","benim","senin","onun","bizim","sizin",
      "şimdi","bugün","yarın","dün","sabah","öğle","akşam","gece","hafta","ay",
      "para","iş","hayat","dünya","ülke","şehir","sokak","park","deniz","dağ",
      "ekmek","et","sebze","meyve","çay","kahve","şeker","tuz","yağ","bal",
      "masa","sandalye","yatak","koltuk","dolap","raf","pencere","tavan","zemin","duvar",
      "ağaç","çiçek","yaprak","dal","kök","toprak","taş","kumsal","nehir","göl",
      "at","kedi","köpek","kuş","balık","arı","sincap","tavşan","aslan","kurt",
      "kırmızı","mavi","yeşil","sarı","siyah","beyaz","mor","turuncu","pembe","gri",
      "sıcak","soğuk","ıslak","kuru","öfkeli","mutlu","üzgün","yorgun","şaşkın","hazır",
      "açık","kapalı","dolu","boş","hızlı","yavaş","yumuşak","sert","hafif","ağır",
      "söz","ses","renk","ad","isim","sayı","soru","cevap","haber","yorum",
      "yüz","el","ayak","kol","omuz","diz","alın","burun","ağız","kulak",
      "şarkı","müzik","dans","resim","film","oyun","spor","koşu","yüzme","bisiklet",
      "sabun","havlu","diş","saç","kalem","defter","çanta","anahtar","saat","gözlük",
      "uçak","tren","otobüs","taksi","gemi","bisiklet","motosiklet","kamyon","ambulans","itfaiye",
      "doktor","hemşire","öğretmen","mühendis","avukat","polis","asker","pilot","şef","ressam",
      "oda","salon","mutfak","banyo","bahçe","çatı","merdiven","kapı","balkon","bodrum",
      "yemek","içmek","uyumak","kalkmak","koşmak","durmak","dönmek","bakmak","dinlemek","konuşmak",
      "yeni","eski","temiz","kirli","geniş","dar","düz","eğri","doğru","yanlış",
      "tatlı","acı","ekşi","tuzlu","baharatlı","hafif","ağır","sert","yumuşak","pürüzsüz"
    ],
    common: [
      "anlamak","başlamak","bitirmek","devam","etmek","göstermek","istemek","karar","vermek",
      "kullanmak","öğrenmek","tutmak","uygulamak","yapmak","yardım","zorlanmak",
      "bulmak","çıkarmak","düzeltmek","geliştirmek","hazırlamak","ilerlemek","kazanmak",
      "önemli","gerekli","doğru","yanlış","kolay","zor","farklı","aynı","yeni","eski",
      "gerçek","özel","genel","resmi","sosyal","ekonomik","kültürel","tarihsel",
      "program","sistem","proje","konu","durum","sonuç","neden","amaç","yöntem","süreç",
      "çözüm","sorun","fırsat","risk","değer","anlam","ilişki","etki","güç","hak",
      "teknoloji","bilim","sanat","müzik","spor","sağlık","eğitim","politika",
      "internet","bilgisayar","telefon","ekran","uygulama","yazılım","veri","dosya",
      "toplum","devlet","hükümet","kanun","yasa","kurul","kurum","şirket","marka",
      "gelecek","geçmiş","şimdiki","değişim","gelişme","büyüme","başlangıç","son",
      "başarı","başarısızlık","deneyim","tecrübe","beceri","yetenek","motivasyon","hedef",
      "strateji","plan","proje","bütçe","kaynak","zaman","enerji","çaba","emek","gayret",
      "toplantı","sunum","rapor","belge","sözleşme","anlaşma","teklif","ret","onay","izin",
      "müşteri","çalışan","yönetici","patron","ortak","rakip","tedarikçi","dağıtıcı",
      "üretim","tüketim","ihracat","ithalat","yatırım","kâr","zarar","gelir","gider","vergi",
      "araştırma","geliştirme","inovasyon","tasarım","test","analiz","değerlendirme","uygulama",
      "bağlantı","iletişim","mesaj","bildirim","güncelleme","yükleme","indirme","paylaşım",
      "güvenlik","gizlilik","şifre","koruma","risk","tehdit","açık","kapalı","erişim",
      "sağlıklı","hasta","ilaç","tedavi","ameliyat","muayene","tanı","semptom","iyileşme",
      "mutfak","tarif","malzeme","pişirme","servis","lezzet","aroma","doku","sunum",
      "seyahat","tur","tatil","otel","bilet","pasaport","vize","rezervasyon","iptal",
      "spor","antrenman","maç","turnuva","takım","oyuncu","koç","hakem","puan","gol",
      "film","dizi","oyun","tiyatro","konser","sergi","festival","etkinlik","organizasyon",
      "hava","sıcaklık","nem","rüzgar","yağmur","kar","fırtına","güneş","bulut","sis",
      "doğa","çevre","orman","nehir","okyanus","kıta","ülke","bölge","şehir","köy"
    ],
    advanced: [
      "algılamak","analiz","etmek","araştırmak","belgelemek","değerlendirmek","deneyimlemek",
      "geliştirmek","hesaplamak","ilerleme","kaydetmek","öngörmek","plânlamak","sorgulamak",
      "tanımlamak","yorumlamak","kavram","metodoloji","strateji","perspektif",
      "analitik","bütüncül","eleştirel","kapsamlı","sistematik","sürdürülebilir","verimli",
      "felsefe","psikoloji","sosyoloji","ekonomi","matematik","fizik","kimya","biyoloji",
      "demokratik","ideoloji","paradigma","epistemoloji","ontoloji","hermeneutik",
      "küreselleşme","sanayileşme","modernleşme","dijitalleşme","sürdürülebilirlik",
      "başarı","zorluk","engel","hedef","motivasyon","yetenek","beceri","deneyim",
      "yaratıcılık","yenilikçilik","girişimcilik","liderlik","çalışkanlık","disiplin",
      "iletişim","empati","saygı","güven","dürüstlük","adalet","özgürlük","eşitlik",
      "çevre","ekosistem","biyoçeşitlilik","iklim","doğa","kaynaklar","koruma","atık",
      "algoritma","veri","yapay","zeka","makine","öğrenmesi","derin","öğrenme","sinir","ağı",
      "kuantum","hesaplama","siber","güvenlik","bulut","blokzincir","kripto","meta","sanal",
      "nörobilim","genomik","proteomik","biyoinformatik","sentetik","biyoloji",
      "termodinamik","elektromanyetizma","kuantum","mekaniği","rölativiyet","astrofizik",
      "antropoloji","arkeoloji","linguistik","semiyotik","fenomenoloji","diyalektik",
      "kapitalizm","sosyalizm","liberalizm","muhafazakarlık","anarşizm","federalizm",
      "psikoanaliz","davranışçılık","hümanizm","varoluşculuk","nihilizm","pragmatizm",
      "sürrealizm","empresyonizm","kübizm","dadaizm","minimalizm","postmodernizm",
      "mütevazı","erdemli","fedakâr","kararlı","azimli","çalışkan","titiz","sabırlı","cömert","şefkatli",
      "müzakere","diplomasi","arabuluculuk","uzlaşı","diyaloğ","uzlaşma","taviz","anlaşmazlık",
      "bağımsızlık","egemenlik","demokrasi","cumhuriyet","monarşi","oligarşi","teokrasi",
      "enflasyon","deflasyon","stagflasyon","resesyon","büyüme","kalkınma","gelişme","refah",
      "uluslararası","çokuluslu","bölgesel","yerel","küresel","ulusal","devletler","arası"
    ]
  },
  en: {
    basic: [
      "the","and","for","are","but","not","you","all","can","her","was","one","our","out","day",
      "get","has","him","his","how","man","new","now","old","see","two","way","who","boy","did",
      "its","let","put","say","she","too","use","about","after","again","also","back","been",
      "came","come","does","down","each","even","from","give","good","great","hand","have",
      "here","high","home","into","keep","know","last","left","life","like","line","long",
      "look","made","make","many","more","most","move","much","must","name","need","next",
      "only","open","other","over","part","play","same","show","some","still","such","take",
      "tell","than","that","them","then","there","they","this","time","turn","under","very",
      "want","well","went","were","what","when","where","which","while","with","word","work",
      "year","your","big","small","fast","slow","good","bad","hot","cold","long","short",
      "dog","cat","bird","fish","tree","leaf","root","rock","sand","lake","hill","sky",
      "red","blue","green","yellow","black","white","gray","pink","brown","gold","dark","light",
      "food","milk","rice","meat","soup","cake","salt","oil","egg","tea","cup","pen","bag",
      "door","wall","roof","room","bed","chair","desk","book","lamp","clock","key","hat",
      "run","jump","walk","talk","sing","read","draw","cook","swim","fly","help","stop",
      "nice","warm","cool","soft","hard","full","free","safe","sharp","deep","wide","thin",
      "sun","moon","star","wind","rain","snow","storm","cloud","fog","ice","fire","water",
      "road","path","hall","gate","step","yard","town","farm","lake","hill","cave","land",
      "hand","foot","arm","leg","eye","ear","nose","lip","hair","skin","bone","heart","mind",
      "feel","hear","seen","told","hold","kept","sent","gone","done","got","brought","thought"
    ],
    common: [
      "about","above","across","action","almost","already","always","another","anyone","around",
      "become","before","behind","believe","between","beyond","bottom","brought","budget","build",
      "cannot","career","center","change","charge","choice","choose","claim","clear","close",
      "coming","common","create","decide","design","detail","develop","direct","during","effort",
      "either","enough","entire","expect","family","famous","follow","former","found","front",
      "future","general","given","global","going","great","group","growth","happen","having",
      "health","heavy","higher","history","however","human","important","include","inside",
      "instead","issue","itself","likely","little","local","major","market","matter","measure",
      "member","method","middle","might","model","moment","money","month","morning","mother",
      "mountain","moving","national","natural","nearly","never","notice","number","object",
      "office","often","online","order","other","others","outside","overall","parent","people",
      "person","place","point","power","present","pretty","price","private","problem","program",
      "project","provide","public","quality","question","quickly","rather","reason","report",
      "result","right","school","second","service","should","simple","single","social","something",
      "system","taken","talking","teacher","together","toward","travel","trying","twenty","until",
      "update","using","various","version","village","visit","voice","wanted","whether","window",
      "within","without","working","written","indeed","inform","interest","invest","involve","judge",
      "launch","leader","listen","master","mutual","native","network","nothing","notice","option",
      "output","player","policy","prefer","protect","publish","purpose","pursue","recall","reduce",
      "relate","remain","remove","repeat","review","reward","satisfy","section","select","series",
      "signal","simple","source","spread","status","stream","strong","studio","submit","supply",
      "surely","survey","switch","symbol","target","theory","though","threat","useful","value",
      "verify","vision","volume","wealth","weight","widely","winner","wonder","worthy","actual"
    ],
    advanced: [
      "accommodate","acknowledge","acquisition","administration","adolescent","affiliated",
      "allocation","ambiguous","ambivalent","amplification","analytical","anticipate","arbitrary",
      "architecture","articulate","assessment","asymmetric","autonomous","breakthrough","bureaucratic",
      "capability","categorical","chronological","circumference","collaboration","commentary",
      "comprehensive","conceptual","configuration","consciousness","consequence","contemporary",
      "controversial","correlation","culmination","decomposition","deliberate","demonstrate",
      "determination","differentiation","disadvantageous","disciplinary","discretionary",
      "documentation","domination","efficiency","elaboration","enlightenment","environmental",
      "equilibrium","equivalent","evaluation","evolutionary","exceptional","exhaustive",
      "experimental","exploration","exponential","extraordinary","fabrication","facilitation",
      "feasibility","formulation","fragmentation","functionality","generalization","governance",
      "groundbreaking","hypothesis","identification","implementation","implications","independence",
      "infrastructure","initialization","innovation","intellectual","intervention","investigation",
      "jurisdiction","justification","methodology","minimization","miscellaneous","modification",
      "negotiation","nevertheless","normalization","optimization","organization","orientation",
      "participation","philosophical","photosynthesis","precipitation","presentation","prioritization",
      "professional","proportional","quantitative","recommendations","reconciliation","representation",
      "responsibility","sophisticated","specialization","standardization","sustainability",
      "accountability","accomplishment","acknowledgement","administration","amplification",
      "categorization","characterization","circumference","classification","collaboration",
      "communication","compensation","competitiveness","comprehension","concentration","configuration",
      "conscientious","consolidation","contamination","contemplation","contradiction","contribution",
      "controversial","crystallization","demonstration","differentiation","disadvantageous",
      "disintegration","documentation","electromagnetic","encouragement","enlightenment","entrepreneurial",
      "environmental","equilibrium","establishment","extraordinary","fragmentation","functionality",
      "globalization","headquarters","humanitarian","identification","implementation","incompatibility",
      "indispensable","industrialization","infrastructure","instrumentation","interdependence",
      "interpretation","investigation","manifestation","maximization","misinterpretation",
      "multidisciplinary","nanotechnology","paradoxical","perseverance","phenomenological",
      "philosophical","predominantly","proportionate","rationalization","rehabilitation",
      "reorganization","representative","revolutionary","satisfactorily","sophistication",
      "transformation","transportation","understanding","unprecedented","vulnerability","authorization"
    ]
  }
};

// Turkish quotes — Alıntılar
const QUOTES_TR = [
  "Düşünüyorum, öyleyse varım.",
  "Bir adım atmak, bin düşünceden değerlidir.",
  "Başarı, hazırlık ile fırsatın buluştuğu yerdir.",
  "Değişim, her şeyin temelidir. Akarken bile aynı nehire iki kez giremezsin.",
  "En büyük zafer, kendini yenebilmektir.",
  "Bilgelik, doğru soruları sormakla başlar.",
  "Hayat kısa, sanat uzun, fırsat uçucu, deney yanıltıcı, hüküm güçtür.",
  "Eğitim, geleceğin anahtarıdır ve onu kullanmayı sen belirlersin.",
  "Hayal gücü, bilgiden daha önemlidir. Bilgi sınırlıdır, hayal gücü ise dünyayı çevreler.",
  "Bir şeyi çok istersen, tüm evren seni oraya ulaştırmak için komplo kurar.",
  "Yaşamak tehlikeli bir girişimdir; hiç kimse sağ kurtulamaz.",
  "Başkalarına nasıl davranmak istiyorsanız, onlara öyle davranın.",
  "Bugünü eriyi ve yarını kurtar; dün geçip gitti.",
  "Okumak insanı eksiksiz yapar, konuşmak onu hazır kılar, yazmak ise onu kesin yapar.",
  "Sabır acıdır ama meyvesi tatlıdır.",
  "Bir mum diğer bir mumu yakmakla azalmaz; bu nedenle paylaşın.",
  "Zorluklar, insanı yıkabilmek için değil, inşa edebilmek için vardır.",
  "Gerçek bilgelik, ne bilmediğini bilmektir.",
  "İnsanlar hata yapar; defalarca aynı hatayı yapıyorsa aptalca davranıyor demektir.",
  "Mutluluk bir servet değil, bir seçimdir."
];

// English quotes
const QUOTES_EN = [
  "The only way to do great work is to love what you do.",
  "In the beginning was the word, and the word was with possibility.",
  "Life is what happens when you are busy making other plans.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you can imagine is real.",
  "The journey of a thousand miles begins with one single step.",
  "Two roads diverged in a wood and I took the one less traveled by.",
  "You miss one hundred percent of the shots you never take.",
  "Whether you think you can or think you cannot, you are right.",
  "In the middle of every difficulty lies opportunity.",
  "Imagination is more important than knowledge for knowledge is limited.",
  "The unexamined life is not worth living.",
  "To be or not to be that is the question.",
  "All that glitters is not gold and not all who wander are lost.",
  "We are what we repeatedly do and excellence is not an act but a habit.",
  "The greatest glory in living lies not in never falling but in rising every time we fall.",
  "Spread love everywhere you go and let no one ever come to you without leaving happier.",
  "When you reach the end of your rope tie a knot in it and hang on.",
  "Always remember that you are absolutely unique just like everyone else."
];

window.WORD_LISTS = WORD_LISTS;
window.QUOTES_TR = QUOTES_TR;
window.QUOTES_EN = QUOTES_EN;
